export const FETCH_RECORDS = 'FETCH_RECORDS';
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';
export const FETCH_RECORDS_FAIL = 'FETCH_RECORDS_FAIL';

export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAIL = 'ADD_RECORD_FAIL';

export const CLEAR_RECORDS = 'CLEAR_RECORDS';
export const CLEAR_RECORDS_SUCCESS = 'CLEAR_RECORDS_SUCCESS';
export const CLEAR_RECORDS_FAIL = 'CLEAR_RECORDS_FAIL';